---
  - name: Launch job
    launch_awx_job:
      url: "{{ url }}"
      user: "{{ user }}"
      password: "{{ password }}"
      job: "{{ job }}"
      credential: "{{ credential }}"
    no_log: True
